BATCH_SIZE = 30
LEARN_RATE = 5e-5
EPOCH = 10
NUM_LABELS = 61

LabeltoTeamsDict = {
    0: 'Irrelavant',
    1: 'Milwaukee Bucks',
    2: 'Boston Celtics',
    3: 'Philadelphia 76ers',
    4: 'Cleveland Cavaliers',
    5: 'New York Knicks',
    6: 'Brooklyn Nets',
    7: 'Atlanta Hawks',
    8: 'Miami Heat',
    9: 'Toronto Raptors',
    10: 'Chicago Bulls',
    11: 'Indiana Pacers',
    12: 'Washigton Wizards', 
    13: 'Orlando Magic',
    14: 'Charlotte Hornets',
    15: 'Detroit Pistons',
    16: 'Denver Nuggets',
    17: 'Memphis Grizzlies',
    18: 'Sacramento Kings',
    19: 'Phoenix Suns',
    20: 'LA Clippers',
    21: 'Golden State Warriors',
    22: 'Los Angeles Lakers',
    23: 'Minnesota Timberwolves',
    24: 'New Orleans Pelicans',
    25: 'Oklahoma City Thunder',
    26: 'Dallas Mavericks',
    27: 'Utah Jazz',
    28: 'Portland Trail Blazers',
    29: 'Houston Rockets',
    30: 'San Antonio Spurs',
    -1: 'Negative Milwaukee Bucks',
    -2: 'Negative Boston Celtics',
    -3: 'Negative Philadelphia 76ers',
    -4: 'Negative Cleveland Cavaliers',
    -5: 'Negative New York Knicks',
    -6: 'Negative Brooklyn Nets',
    -7: 'Negative Atlanta Hawks',
    -8: 'Negative Miami Heat',
    -9: 'Negative Toronto Raptors',
    -10: 'Negative Chicago Bulls',
    -11: 'Negative Indiana Pacers',
    -12: 'Negative Washigton Wizards', 
    -13: 'Negative Orlando Magic',
    -14: 'Negative Charlotte Hornets',
    -15: 'Negative Detroit Pistons',
    -16: 'Negative Denver Nuggets',
    -17: 'Negative Memphis Grizzlies',
    -18: 'Negative Sacramento Kings',
    -19: 'Negative Phoenix Suns',
    -20: 'Negative LA Clippers',
    -21: 'Negative Golden State Warriors',
    -22: 'Negative Los Angeles Lakers',
    -23: 'Negative Minnesota Timberwolves',
    -24: 'Negative New Orleans Pelicans',
    -25: 'Negative Oklahoma City Thunder',
    -26: 'Negative Dallas Mavericks',
    -27: 'Negative Utah Jazz',
    -28: 'Negative Portland Trail Blazers',
    -29: 'Negative Houston Rockets',
    -30: 'Negative San Antonio Spurs'
}