BATCH_SIZE = 30
LEARN_RATE = 5e-5
EPOCH = 10
NUM_LABELS = 61

LabeltoTeamsDict = {
    0: 'Irrelavant',
    1: 'Milwaukee Bucks',
    2: 'Boston Celtics',
    3: 'Philadelphia 76ers',
    4: 'Cleveland Cavaliers',
    5: 'New York Knicks',
    6: 'Brooklyn Nets',
    7: 'Atlanta Hawks',
    8: 'Miami Heat',
    9: 'Toronto Raptors',
    10: 'Chicago Bulls',
    11: 'Indiana Pacers',
    12: 'Washigton Wizards', 
    13: 'Orlando Magic',
    14: 'Charlotte Hornets',
    15: 'Detroit Pistons',
    16: 'Denver Nuggets',
    17: 'Memphis Grizzlies',
    18: 'Sacramento Kings',
    19: 'Phoenix Suns',
    20: 'LA Clippers',
    21: 'Golden State Warriors',
    22: 'Los Angeles Lakers',
    23: 'Minnesota Timberwolves',
    24: 'New Orleans Pelicans',
    25: 'Oklahoma City Thunder',
    26: 'Dallas Mavericks',
    27: 'Utah Jazz',
    28: 'Portland Trail Blazers',
    29: 'Houston Rockets',
    30: 'San Antonio Spurs',
    31: 'Negative Milwaukee Bucks',
    32: 'Negative Boston Celtics',
    33: 'Negative Philadelphia 76ers',
    34: 'Negative Cleveland Cavaliers',
    35: 'Negative New York Knicks',
    36: 'Negative Brooklyn Nets',
    37: 'Negative Atlanta Hawks',
    38: 'Negative Miami Heat',
    39: 'Negative Toronto Raptors',
    40: 'Negative Chicago Bulls',
    41: 'Negative Indiana Pacers',
    42: 'Negative Washigton Wizards', 
    43: 'Negative Orlando Magic',
    44: 'Negative Charlotte Hornets',
    45: 'Negative Detroit Pistons',
    46: 'Negative Denver Nuggets',
    47: 'Negative Memphis Grizzlies',
    48: 'Negative Sacramento Kings',
    49: 'Negative Phoenix Suns',
    50: 'Negative LA Clippers',
    51: 'Negative Golden State Warriors',
    52: 'Negative Los Angeles Lakers',
    53: 'Negative Minnesota Timberwolves',
    54: 'Negative New Orleans Pelicans',
    55: 'Negative Oklahoma City Thunder',
    56: 'Negative Dallas Mavericks',
    57: 'Negative Utah Jazz',
    58: 'Negative Portland Trail Blazers',
    59: 'Negative Houston Rockets',
    60: 'Negative San Antonio Spurs'
}